services:
  spacexp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spacexp-app
    ports:
      - "3000:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - app-network

  spacexp-selenium:
    image: selenium/standalone-chrome:latest
    container_name: spacexp-selenium
    shm_size: '2gb'
    tmpfs:
      - /tmp
    cap_add:
      - SYS_ADMIN
    depends_on:
      spacexp-app:
        condition: service_healthy
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
