services:
  app:
    build: .
    container_name: aws-devops-pipeline-app-1
    ports:
      - "3000:3000"
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: aws-devops-pipeline-selenium-1
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: '2gb'
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
