version: '3.8'

services:
  spacexp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spacexp-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  spacexp-selenium:
    image: selenium/standalone-chrome:latest
    container_name: spacexp-selenium
    shm_size: '2gb'
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
